"""empty message

Revision ID: 39d148fe9e0f
Revises: 
Create Date: 2024-10-24 16:13:02.125486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39d148fe9e0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_date', 'expenses', ['date'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # Add new columns with a default value
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('selling_price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))

    # Update existing rows to set default values
    op.execute("UPDATE products SET cost_price = 0.0 WHERE cost_price IS NULL")
    op.execute("UPDATE products SET selling_price = 0.0 WHERE selling_price IS NULL")

    op.drop_index('ix_product_category_id', table_name='products')
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    op.drop_column('products', 'price')
    op.create_index('ix_user_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_role', table_name='users')
    op.add_column('products', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index('ix_product_category_id', 'products', ['category_id'], unique=False)
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'cost_price')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    op.drop_index('ix_expense_date', table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
