"""empty message

Revision ID: 562ea69bbe56
Revises: 
Create Date: 2024-10-24 18:32:04.710896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562ea69bbe56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expenses_date'), 'expenses', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_date'), table_name='expenses')
    # ### end Alembic commands ###
